# Generated by Django 6.1.1 on 2026-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoRealSaber11',
            fields=[
                ('id_resultado_real', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('puntaje_global', models.IntegerField(blank=True, null=True)),
                ('lectura_critica', models.IntegerField(blank=True, null=True)),
                ('matematicas', models.IntegerField(blank=True, null=True)),
                ('sociales_ciudadanas', models.IntegerField(blank=True, null=True)),
                ('ciencias_naturales', models.IntegerField(blank=True, null=True)),
                ('ingles', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'resultado_reales_saber_11',
            },
        ),
    ]
