# Generated by Django 6.1.1 on 2026-09-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('resultados', '0001_initial'),
        ('subirArchivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadorealsaber11',
            name='id_carga',
            field=models.ForeignKey(db_column='id_carga', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='subirArchivos.cargaarchivo'),
        ),
        migrations.AddField(
            model_name='resultadorealsaber11',
            name='id_institucion',
            field=models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucioneducativa'),
        ),
    ]
