# Generated by Django 6.1.1 on 2026-10-06 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarDatos', '0001_initial'),
        ('resultados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadorealsaber11',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadorealsaber11',
            name='id_carga',
            field=models.ForeignKey(db_column='id_carga', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cargarDatos.cargaarchivo'),
        ),
    ]
