# Generated by Django 6.1.1 on 2026-09-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicioSesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('estado_importacion', models.CharField(default='pendiente', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='inicioSesion.usuario')),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
    ]
