# Generated by Django 6.1.1 on 2026-09-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_dane', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_institucion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'institucion_educativa',
            },
        ),
    ]
