# Generated by Django 6.1.1 on 2026-09-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(default='CC', max_length=20)),
                ('numero_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('id_institucion', models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucioneducativa')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='inicioSesion.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
