# Generated by Django 6.1.1 on 2026-10-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioSesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(default='C.C', max_length=20),
        ),
    ]
